"""Room context assembly: transcript cursors, layered stateless context,
and durable rolling summaries.

Two context strategies, chosen per participant from the *capability* of the
bound adapter:

Persistent agents (Codex app-server threads, ACP persistent sessions):
    ``transcript_cursor`` tracks the last delivered turn index per
    participant.  Only turns newer than the cursor go into the next prompt --
    the thread already owns everything older.  When the physical runtime
    restarts or the thread is rebuilt (``restart_session`` /
    ``resume_from_storage``), the cursor resets and the next turn uses a
    rehydrated context: Static Persona Kernel + durable room summary +
    relevant memories + recent raw turns.

Stateless agents:
    never receive the whole history either.  A layered context is assembled:
    kernel, room/scenario definition, long-term rolling summary, relevant
    historical retrieval, relationship state, important events, a bounded
    recent raw-turn window, and the current turn.  Full history stays in the
    database; only the prompt is bounded.

The rolling summary is generated by the model (one call every
``summary_every_turns`` beyond the raw window) and preserves key facts,
relationship shifts, commitments, conflicts, viewpoint changes, positions,
important events, open topics, long-term goals, and known user information.
"""

from __future__ import annotations

import asyncio
import json
import re
from dataclasses import dataclass, field
from typing import Any

from persona_continuum.room.context_packer import (
    conservative_budget,
    extract_older_user_facts,
)
from persona_continuum.runtime.turn_normalizer import normalize_turn, normalize_turn_for_prompt

SUMMARY_PROMPT_INTRO = (
    "You maintain a bounded factual continuity summary for a long-running room "
    "conversation. This is a data-compression task, not roleplay: never speak as "
    "any character, never continue the conversation, never copy dialogue "
    "verbatim, and never invent events.\n"
    "Preserve only what must survive for continuity: important facts about the "
    "participants, relationship changes, promises and commitments, important "
    "shared events, unresolved topics, future plans, durable preferences, "
    "conflicts and reconciliations, and anything explicitly asked to be "
    "remembered.\n"
    "Merge duplicates, drop obsolete low-value detail, and keep it short. "
    "Output the structured summary only."
)

SUMMARY_SCHEMA: dict[str, Any] = {
    "type": "object",
    "properties": {
        "key_facts": {"type": "array", "items": {"type": "string"}},
        "relationship_shifts": {"type": "array", "items": {"type": "string"}},
        "commitments": {"type": "array", "items": {"type": "string"}},
        "conflicts": {"type": "array", "items": {"type": "string"}},
        "viewpoint_changes": {"type": "array", "items": {"type": "string"}},
        "positions": {"type": "array", "items": {"type": "string"}},
        "important_events": {"type": "array", "items": {"type": "string"}},
        "open_topics": {"type": "array", "items": {"type": "string"}},
        "long_term_goals": {"type": "array", "items": {"type": "string"}},
        "known_user_info": {"type": "array", "items": {"type": "string"}},
    },
    "required": ["key_facts", "open_topics"],
}


#: A scene/style migration once wrote a raw transcript dump into
#: ``rolling_summary`` under this header.  That is evidence, not a summary, and
#: must never be treated as the canonical rolling summary.
LEGACY_SUMMARY_MARKER = "## Scene / relationship evidence"
#: Canonical rolling summaries carry this version.  Anything missing or lower is
#: legacy data and is ignored at runtime.
CANONICAL_SUMMARY_VERSION = 2


def is_canonical_summary(text: Any, version: Any = None) -> bool:
    """Whether a stored ``rolling_summary`` may be used as the canonical one.

    Requires BOTH a recognised version and content that is not the legacy
    evidence dump.  "The field contains a string" is not sufficient -- treating
    it as sufficient is exactly how the migration's transcript dump came to be
    injected into prompts as if it were a summary.
    """

    if not isinstance(text, str) or not text.strip():
        return False
    if text.lstrip().startswith(LEGACY_SUMMARY_MARKER):
        return False
    try:
        return int(version) >= CANONICAL_SUMMARY_VERSION
    except (TypeError, ValueError):
        return False


def estimate_tokens(text: Any) -> int:
    """CJK-aware token estimate (CJK per character, ~4 chars elsewhere).

    A flat ``len // 4`` under-counts Chinese by roughly 4x, which is exactly the
    wrong direction for the budgets that matter here.
    """

    if not text:
        return 0
    value = text if isinstance(text, str) else json.dumps(text, ensure_ascii=False, default=str)
    cjk = len(re.findall(r"[\u3400-\u9fff\uf900-\ufaff]", value))
    return cjk + max(0, len(value) - cjk) // 4


def render_summary_markdown(
    summary: dict[str, Any],
    *,
    max_chars: int | None = None,
    max_tokens: int | None = None,
) -> str:
    labels = {
        "key_facts": "Key facts",
        "relationship_shifts": "Relationship shifts",
        "commitments": "Commitments",
        "conflicts": "Conflicts",
        "viewpoint_changes": "Viewpoint changes",
        "positions": "Positions",
        "important_events": "Important events",
        "open_topics": "Open topics",
        "long_term_goals": "Long-term goals",
        "known_user_info": "Known user information",
    }
    lines: list[str] = []
    for key, label in labels.items():
        values = [str(item) for item in (summary.get(key) or []) if str(item).strip()]
        if values:
            lines.append(f"- {label}: " + "; ".join(values))
    header = "## Room Long-term Summary"
    if max_chars is None and max_tokens is None:
        return header + "\n" + "\n".join(lines)
    # A summary is a bounded digest, not a second transcript: keep whole
    # sections while BOTH the character and token ceilings still hold, then stop.
    kept: list[str] = []
    used_chars = len(header)
    used_tokens = estimate_tokens(header)
    for line in lines:
        next_chars = used_chars + len(line) + 1
        next_tokens = used_tokens + estimate_tokens(line) + 1
        if max_chars is not None and max_chars > 0 and next_chars > max_chars:
            break
        if max_tokens is not None and max_tokens > 0 and next_tokens > max_tokens:
            break
        kept.append(line)
        used_chars, used_tokens = next_chars, next_tokens
    return header + ("\n" + "\n".join(kept) if kept else "")


@dataclass(slots=True)
class RoomTurnContext:
    turns: list[dict[str, Any]]
    mode: str  # full | delta | windowed | rehydrated | transport_truncated
    cursor_before: int
    summary_block: str | None = None
    # Index the participant's thread owns everything up to after this turn is
    # delivered; used to advance the cursor exactly.
    cursor_after: int = 0
    # Whether this participant runs on a persistent thread that should track a
    # transcript cursor at all (False for stateless layered-context adapters).
    track_cursor: bool = False
    # Deterministically salvaged statements from turns that fell outside the
    # transported window.  Never empty when ``mode == transport_truncated``
    # and the room had older user turns.
    salvaged_facts: list[str] = field(default_factory=list)


def _estimate_transcript_bytes(turns: list[dict[str, Any]]) -> int:
    total = 0
    for turn in turns:
        if not isinstance(turn, dict):
            continue
        total += len(str(turn.get("content") or "").encode("utf-8"))
        total += len(str(turn.get("speaker_name") or "").encode("utf-8"))
    return total


def _trim_to_budget(
    turns: list[dict[str, Any]],
    budget_bytes: int,
    *,
    per_turn_chars: int = 600,
) -> list[dict[str, Any]]:
    """Keep the newest turns (and any user turn) inside a byte budget.

    Deterministic, no model call: newest-first greedy fill, user turns are
    never dropped before assistant turns because they carry the case facts.
    Per-turn cost uses the same estimator as the budget decision
    (content + speaker_name), so the result never exceeds the budget it
    was trimmed to (§32).  Both passes collect surviving ORIGINAL indices
    and the result is rebuilt in transcript order -- collecting turns
    directly would reverse() into an [all assistant]+[all user] interleave
    that scrambles the dialogue.
    """

    if _estimate_transcript_bytes(turns) <= budget_bytes:
        return list(turns)

    kept: list[tuple[int, dict[str, Any]]] = []
    used = 0
    # Pass 1: newest-first, user turns only.
    for index in range(len(turns) - 1, -1, -1):
        turn = turns[index]
        if not isinstance(turn, dict):
            continue
        if turn.get("participant_id") != "user":
            continue
        cost = _estimate_transcript_bytes([turn])
        if used + cost > budget_bytes:
            continue
        kept.append((index, turn))
        used += cost
    # Pass 2: fill the remainder with the newest assistant turns.
    for index in range(len(turns) - 1, -1, -1):
        turn = turns[index]
        if not isinstance(turn, dict):
            continue
        if turn.get("participant_id") == "user":
            continue
        content = str(turn.get("content") or "")
        cost = _estimate_transcript_bytes([turn])
        if used + cost > budget_bytes:
            remaining = budget_bytes - used
            if remaining <= 64:
                continue
            clipped = dict(turn)
            clipped["content"] = content[: per_turn_chars // 3] + "…"
            clipped_cost = _estimate_transcript_bytes([clipped])
            if used + clipped_cost > budget_bytes:
                continue
            kept.append((index, clipped))
            used += clipped_cost
            continue
        kept.append((index, turn))
        used += cost
    kept.sort(key=lambda pair: pair[0])
    return [turn for _, turn in kept]


def _turn_token_cost(turn: dict[str, Any]) -> int:
    """Token cost of one transcript entry as the model will actually read it."""

    if not isinstance(turn, dict):
        return 0
    return estimate_tokens(str(turn.get("content") or "")) + estimate_tokens(
        str(turn.get("speaker_name") or turn.get("participant_id") or "")
    )


def recent_window_start(
    transcript: list[dict[str, Any]],
    *,
    message_window: int,
    token_budget: int | None,
) -> int:
    """Index of the first entry that belongs to the recent raw window.

    The recent window is the PRIMARY working-memory selection, and its unit is
    a **token budget**, not a message count: "嗯" and a 3000-character essay are
    both one message, so a count can neither protect a weak model nor describe
    a strong one.  ``message_window`` remains as a secondary cap and as the
    only rule when no token budget is configured (the historical behaviour).

    Deterministic and side-effect free, so the same function defines both the
    turns sent to the model and the eviction boundary handed to the
    summariser.  If those two disagreed, turns would drop out of the window
    without ever being folded into a summary -- the orphan-turn hole this
    exists to close.

    The newest entry is always kept even when it alone exceeds the budget: it
    is usually the message being answered, and the transport guard is the
    correct place to refuse an impossible single message.
    """

    total = len(transcript or [])
    if total == 0:
        return 0
    cap = max(1, int(message_window))
    if token_budget is None:
        return max(0, total - cap)
    budget = max(0, int(token_budget))
    start = total
    used = 0
    for kept, index in enumerate(range(total - 1, -1, -1)):
        if kept >= cap:
            break
        cost = _turn_token_cost(transcript[index])
        if kept > 0 and used + cost > budget:
            break
        start = index
        used += cost
    return max(0, start)


@dataclass
class RoomContextManager:
    """Owns per-participant cursors and context-mode decisions."""

    cursor_enabled: bool = True
    raw_window: int = 8
    summary_every_turns: int = 10
    #: Refresh cadence once a summary exists.  Distinct from
    #: ``summary_every_turns`` (the legacy value) so the legacy default keeps
    #: working for callers that do not opt in to the new cadence.
    summary_refresh_every_turns: int = 10
    #: Hard ceiling on the rendered rolling summary.
    summary_max_chars: int = 2400
    #: Token ceiling on the rendered rolling summary (both caps apply).
    summary_output_max_tokens: int = 800
    #: Hard ceiling on what the summariser may be asked to read.
    summary_input_max_tokens: int = 4096
    _cursors: dict[tuple[str, str], int] = field(default_factory=dict)
    _reset_pending: set[tuple[str, str]] = field(default_factory=set)
    delta_sends: int = 0
    rehydrations: int = 0
    _summary_lock: asyncio.Lock = field(default_factory=asyncio.Lock, repr=False)

    @staticmethod
    def _key(room_id: str, participant_id: str) -> tuple[str, str]:
        return (room_id, participant_id)

    def cursor_for(self, room_id: str, participant_id: str) -> int | None:
        return self._cursors.get(self._key(room_id, participant_id))

    def reset_cursor(self, room_id: str, participant_id: str) -> None:
        """Force context rehydration for one participant (thread was lost)."""

        key = self._key(room_id, participant_id)
        self._cursors.pop(key, None)
        self._reset_pending.add(key)

    def clear_room(self, room_id: str) -> None:
        for key in [k for k in self._cursors if k[0] == room_id]:
            self._cursors.pop(key, None)
        self._reset_pending.difference_update({k for k in self._reset_pending if k[0] == room_id})

    def prepare(
        self,
        *,
        room_id: str,
        participant_id: str,
        transcript: list[dict[str, Any]],
        persistent: bool,
        summary_block: str | None = None,
        transport_budget_bytes: int | None = None,
        message_window: int | None = None,
        recent_token_budget: int | None = None,
    ) -> RoomTurnContext:
        """Return the turns + mode that should compose the next prompt.

        ``transport_budget_bytes`` is the share of the adapter's prompt
        transport budget this turn may spend on raw transcript.  When the
        rolling summary is unavailable and the transcript no longer fits,
        the result is a deterministic truncation -- never a silent fallback
        to the full transcript, which is what used to blow past the ARGV
        ceiling and fail the turn with PROMPT_TRANSPORT_LIMIT_EXCEEDED.

        ``message_window`` / ``recent_token_budget`` come from the turn's
        resolved :mod:`persona_continuum.room.context_policy` profile.  The
        token budget is the primary unit; the message count is the cap.  Both
        default to the manager's own construction-time values, so callers that
        do not resolve a policy keep the historical behaviour exactly.
        """

        transcript = [
            {
                **t,
                **normalize_turn_for_prompt(t),
                "content": normalize_turn_for_prompt(t)["spoken_text"],
            }
            for t in transcript
        ]
        key = self._key(room_id, participant_id)
        delivered_through = len(transcript)
        window_cap = self.raw_window if message_window is None else max(1, int(message_window))
        window_start = recent_window_start(
            transcript, message_window=window_cap, token_budget=recent_token_budget
        )
        budget = (
            int(transport_budget_bytes)
            if transport_budget_bytes is not None
            else conservative_budget()
        )
        if persistent and self.cursor_enabled:
            cursor = self._cursors.get(key)
            if cursor is None:
                # Two distinct cold cases:
                # - explicit reset (thread was lost): rehydrate from kernel +
                #   summary + a bounded recent raw window.
                # - never tracked (participant joins a fresh room): deliver the
                #   whole history once so the new thread owns it, then go
                #   incremental.
                if key in self._reset_pending:
                    self._reset_pending.discard(key)
                    if transcript:
                        self.rehydrations += 1
                        return RoomTurnContext(
                            turns=list(transcript[window_start:]),
                            mode="rehydrated",
                            cursor_before=0,
                            summary_block=summary_block,
                            cursor_after=delivered_through,
                            track_cursor=True,
                        )
                    return RoomTurnContext(turns=[], mode="delta", cursor_before=0, cursor_after=0)
                if _estimate_transcript_bytes(transcript) > budget:
                    # A brand-new persistent thread must still be delivered
                    # something that fits on the wire; the older turns are
                    # salvaged as facts instead.
                    self.rehydrations += 1
                    window = _trim_to_budget(transcript, budget)
                    return RoomTurnContext(
                        turns=window,
                        mode="transport_truncated",
                        cursor_before=0,
                        summary_block=summary_block,
                        cursor_after=delivered_through,
                        track_cursor=True,
                        salvaged_facts=extract_older_user_facts(transcript),
                    )
                return RoomTurnContext(
                    turns=list(transcript),
                    mode="full",
                    cursor_before=0,
                    cursor_after=delivered_through,
                    track_cursor=True,
                )
            delta = list(transcript[cursor:])
            self.delta_sends += 1
            # The cursor protects against re-sending history, but a single
            # delta can still be larger than the transport can carry.
            if _estimate_transcript_bytes(delta) > budget:
                self.rehydrations += 1
                delta = _trim_to_budget(delta, budget)
                return RoomTurnContext(
                    turns=delta,
                    mode="transport_truncated",
                    cursor_before=cursor,
                    summary_block=summary_block,
                    cursor_after=delivered_through,
                    track_cursor=True,
                    salvaged_facts=extract_older_user_facts(transcript[cursor:]),
                )
            return RoomTurnContext(
                turns=delta,
                mode="delta",
                cursor_before=cursor,
                summary_block=summary_block,
                cursor_after=delivered_through,
                track_cursor=True,
            )
        # Stateless: bounded layered window instead of unbounded history.
        #
        # HARD RULE: once the transcript no longer fits the recent window (by
        # token budget or by the message cap), the full transcript is never
        # sent again.  It used to be sent whenever a rolling summary happened
        # to be missing (not yet generated, refresh failed, or a refresh was
        # still in flight), which made the prompt grow without bound until the
        # provider refused it.  Older content now reaches the model only as the
        # summary plus retrieved long-term memories; the full transcript stays
        # in the database as history and provenance.
        if window_start > 0:
            window = list(transcript[window_start:])
            if _estimate_transcript_bytes(window) > budget:
                window = _trim_to_budget(window, budget)
                return RoomTurnContext(
                    turns=window,
                    mode="transport_truncated",
                    cursor_before=len(transcript),
                    summary_block=summary_block,
                    cursor_after=delivered_through,
                    salvaged_facts=extract_older_user_facts(transcript),
                )
            return RoomTurnContext(
                turns=window,
                mode="windowed",
                cursor_before=len(transcript),
                summary_block=summary_block,
                cursor_after=delivered_through,
            )
        # History fits inside the raw window: it is the whole context anyway.
        if _estimate_transcript_bytes(transcript) > budget:
            return RoomTurnContext(
                turns=_trim_to_budget(transcript, budget),
                mode="transport_truncated",
                cursor_before=len(transcript),
                summary_block=summary_block,
                cursor_after=delivered_through,
                salvaged_facts=extract_older_user_facts(transcript),
            )
        return RoomTurnContext(
            turns=list(transcript),
            mode="full",
            cursor_before=len(transcript),
            summary_block=summary_block,
            cursor_after=delivered_through,
        )

    def commit(self, room_id: str, participant_id: str, ctx: RoomTurnContext) -> None:
        """Advance the cursor after the prompt was delivered to the runtime."""

        if ctx.track_cursor:
            # A persistent thread now owns everything up to cursor_after.
            self._cursors[self._key(room_id, participant_id)] = ctx.cursor_after
        # Stateless participants keep no cursor; every turn is a fresh window.

    def eviction_boundary(
        self,
        transcript: list[dict[str, Any]],
        *,
        message_window: int | None = None,
        recent_token_budget: int | None = None,
    ) -> int:
        """Index where the recent window starts, i.e. the summary boundary.

        Exposed so the orchestrator can take the SMALLEST window start across
        the room's participants: everything that could have left any
        participant's window must be folded into the shared summary, otherwise
        it becomes an orphan turn -- gone from the prompt and never summarised.
        """

        cap = self.raw_window if message_window is None else max(1, int(message_window))
        return recent_window_start(
            transcript, message_window=cap, token_budget=recent_token_budget
        )

    def should_update_summary(
        self,
        turn_index: int,
        *,
        transcript_len: int | None = None,
        has_summary: bool | None = None,
        eviction_boundary: int | None = None,
    ) -> bool:
        """Whether to (re)build the rolling summary before the next turn.

        The first summary is built as soon as history leaves the recent window
        -- it must not wait for ``2 * raw_window`` turns, because during that
        gap the prompt has no summary to lean on.  After that it refreshes on
        the ``summary_refresh_every_turns`` cadence.

        ``eviction_boundary`` (see :meth:`eviction_boundary`) replaces the
        message-count comparison; when omitted the historical modulo behaviour
        is preserved, so existing callers are unaffected.
        """

        if eviction_boundary is None:
            if turn_index < self.raw_window:
                return False
            if transcript_len is not None and transcript_len <= self.raw_window:
                # Everything still fits in the raw window; nothing to summarize.
                return False
        elif eviction_boundary <= 0:
            # Nothing has left the recent window yet: there is no delta to fold.
            return False
        if has_summary is False:
            # First time history outgrew the window: build one now.
            return True
        if has_summary is None:
            every = max(4, self.summary_every_turns)
        else:
            every = max(2, self.summary_refresh_every_turns)
        return turn_index % every == 0

    async def update_summary(
        self,
        *,
        transcript: list[dict[str, Any]],
        previous_summary: str | None,
        summarize: Any,
        checkpoint: int | None = None,
        eviction_boundary: int | None = None,
        summary_max_chars: int | None = None,
        summary_output_max_tokens: int | None = None,
        summary_input_max_tokens: int | None = None,
    ) -> tuple[str | None, int | None, dict[str, Any]]:
        """Fold the next slice of evicted dialogue into the rolling summary.

        Returns ``(summary, new_checkpoint, report)``.

        Delta-based by construction.  The raw window is still carried verbatim
        in the prompt, so the summariser only ever sees messages that have
        *already left* it, and only those newer than ``checkpoint`` (the index
        the previous summary was built through).  The slice is folded oldest
        first, so the checkpoint advances monotonically and nothing is skipped.

        The assembled payload is held under ``summary_input_max_tokens`` by
        stopping at a message boundary.  It never falls back to the full
        transcript and never truncates a string mid-message.

        ``eviction_boundary`` / ``summary_*`` overrides carry the current
        turn's resolved context profile, so a 1M-context room keeps a far
        richer long-term summary than the local survival profile does.
        """

        input_budget = (
            self.summary_input_max_tokens
            if summary_input_max_tokens is None
            else max(512, int(summary_input_max_tokens))
        )
        output_budget = (
            self.summary_output_max_tokens
            if summary_output_max_tokens is None
            else max(100, int(summary_output_max_tokens))
        )
        char_cap = (
            self.summary_max_chars
            if summary_max_chars is None
            else max(400, int(summary_max_chars))
        )
        report: dict[str, Any] = {
            "input_budget_tokens": input_budget,
            "output_budget_tokens": output_budget,
        }
        if not transcript:
            report["reason"] = "empty_transcript"
            return previous_summary, checkpoint, report

        if eviction_boundary is None:
            boundary = max(0, len(transcript) - self.raw_window)
        else:
            boundary = max(0, min(int(eviction_boundary), len(transcript)))
        report["eviction_boundary"] = boundary
        if boundary <= 0:
            report["reason"] = "nothing_evicted_yet"
            return previous_summary, checkpoint, report

        start = 0 if checkpoint is None else max(0, min(int(checkpoint), boundary))
        report["checkpoint_before"] = start
        if start >= boundary:
            report["reason"] = "no_new_delta"
            return previous_summary, checkpoint, report

        previous_text = normalize_turn(previous_summary or "", actor="summary").spoken_text
        fixed_tokens = estimate_tokens(SUMMARY_PROMPT_INTRO) + estimate_tokens(previous_text)
        budget = max(0, input_budget - fixed_tokens)
        report["previous_summary_tokens"] = estimate_tokens(previous_text)
        report["fixed_prompt_tokens"] = estimate_tokens(SUMMARY_PROMPT_INTRO)

        admitted: list[dict[str, Any]] = []
        delta_tokens = 0
        clipped = 0
        for index in range(start, boundary):
            item = normalize_turn_for_prompt(transcript[index])
            # Only the fields the digester needs; the full normalised envelope
            # carries scene/action bookkeeping that would only burn budget.
            compact = {
                "speaker": item.get("speaker_name") or item.get("participant_id") or "",
                "text": str(item.get("spoken_text") or "").strip(),
            }
            if not compact["text"]:
                continue
            cost = estimate_tokens(json.dumps(compact, ensure_ascii=False))
            if admitted and delta_tokens + cost > budget:
                break
            if not admitted and cost > budget:
                # One oversized message must not break the ceiling.  Clip it to
                # the remaining room (message-level, not payload-tail) and, if
                # even that cannot fit, defer rather than over-spend -- the
                # checkpoint then stays put and the next refresh retries it.
                room = budget - 32  # JSON/envelope headroom
                if room < 16:
                    report["reason"] = "delta_exceeds_budget"
                    return previous_summary, checkpoint, report
                compact["text"] = compact["text"][:room]
                cost = estimate_tokens(json.dumps(compact, ensure_ascii=False))
                if cost > budget:
                    report["reason"] = "delta_exceeds_budget"
                    return previous_summary, checkpoint, report
                clipped += 1
            admitted.append(compact)
            delta_tokens += cost

        if not admitted:
            report["reason"] = "delta_exceeds_budget"
            return previous_summary, checkpoint, report

        new_checkpoint = start + len(admitted)
        payload = {
            "previous_summary": previous_text,
            "new_dialogue_since_last_summary": admitted,
        }
        report.update(
            {
                "delta_messages": len(admitted),
                "delta_tokens": delta_tokens,
                "delta_messages_clipped": clipped,
                "delta_messages_deferred": boundary - new_checkpoint,
                "estimated_input_tokens": fixed_tokens + delta_tokens,
                "checkpoint_after": new_checkpoint,
            }
        )

        async with self._summary_lock:
            try:
                result = await summarize(payload, SUMMARY_SCHEMA)
            except Exception as exc:  # noqa: BLE001
                report["reason"] = f"summarize_failed:{type(exc).__name__}"
                return previous_summary, checkpoint, report
        if not isinstance(result, dict):
            report["reason"] = "summarizer_returned_no_object"
            return previous_summary, checkpoint, report

        rendered = normalize_turn(
            render_summary_markdown(
                result,
                max_chars=char_cap,
                max_tokens=output_budget,
            ),
            actor="summary",
        ).spoken_text
        report["output_tokens"] = estimate_tokens(rendered)
        report["output_chars"] = len(rendered)
        report["reason"] = "ok"
        return rendered, new_checkpoint, report

    def snapshot(self) -> dict[str, Any]:
        return {
            "cursor_enabled": self.cursor_enabled,
            "raw_window": self.raw_window,
            "tracked_participants": len(self._cursors),
            "delta_sends": self.delta_sends,
            "rehydrations": self.rehydrations,
        }


__all__ = [
    "RoomContextManager",
    "RoomTurnContext",
    "SUMMARY_PROMPT_INTRO",
    "SUMMARY_SCHEMA",
    "CANONICAL_SUMMARY_VERSION",
    "LEGACY_SUMMARY_MARKER",
    "is_canonical_summary",
    "recent_window_start",
    "render_summary_markdown",
]
