"""Room context assembly: transcript cursors, layered stateless context,
and durable rolling summaries.

Two context strategies, chosen per participant from the *capability* of the
bound adapter:

Persistent agents (Codex app-server threads, ACP persistent sessions):
    ``transcript_cursor`` tracks the last delivered turn index per
    participant.  Only turns newer than the cursor go into the next prompt --
    the thread already owns everything older.  When the physical runtime
    restarts or the thread is rebuilt (``restart_session`` /
    ``resume_from_storage``), the cursor resets and the next turn uses a
    rehydrated context: Static Persona Kernel + durable room summary +
    relevant memories + recent raw turns.

Stateless agents:
    never receive the whole history either.  A layered context is assembled:
    kernel, room/scenario definition, long-term rolling summary, relevant
    historical retrieval, relationship state, important events, a bounded
    recent raw-turn window, and the current turn.  Full history stays in the
    database; only the prompt is bounded.

The rolling summary is generated by the model (one call every
``summary_every_turns`` beyond the raw window) and preserves key facts,
relationship shifts, commitments, conflicts, viewpoint changes, positions,
important events, open topics, long-term goals, and known user information.
"""

from __future__ import annotations

import asyncio
from dataclasses import dataclass, field
from typing import Any

from persona_continuum.room.context_packer import (
    conservative_budget,
    extract_older_user_facts,
)

SUMMARY_PROMPT_INTRO = (
    "你是 Persona Continuum 的房间上下文管理器。请把以下对话记录压缩成结构化"
    "长期摘要，必须保留：关键事实、关系变化、承诺、冲突、观点变化、人物立场、"
    "重要事件、未解决议题、长期目标、已知的用户信息。不要丢弃任何仍然相关的"
    "约束或未决问题；摘要会作为长期上下文重新注入后续发言。"
)

SUMMARY_SCHEMA: dict[str, Any] = {
    "type": "object",
    "properties": {
        "key_facts": {"type": "array", "items": {"type": "string"}},
        "relationship_shifts": {"type": "array", "items": {"type": "string"}},
        "commitments": {"type": "array", "items": {"type": "string"}},
        "conflicts": {"type": "array", "items": {"type": "string"}},
        "viewpoint_changes": {"type": "array", "items": {"type": "string"}},
        "positions": {"type": "array", "items": {"type": "string"}},
        "important_events": {"type": "array", "items": {"type": "string"}},
        "open_topics": {"type": "array", "items": {"type": "string"}},
        "long_term_goals": {"type": "array", "items": {"type": "string"}},
        "known_user_info": {"type": "array", "items": {"type": "string"}},
    },
    "required": ["key_facts", "open_topics"],
}


def render_summary_markdown(summary: dict[str, Any]) -> str:
    labels = {
        "key_facts": "Key facts",
        "relationship_shifts": "Relationship shifts",
        "commitments": "Commitments",
        "conflicts": "Conflicts",
        "viewpoint_changes": "Viewpoint changes",
        "positions": "Positions",
        "important_events": "Important events",
        "open_topics": "Open topics",
        "long_term_goals": "Long-term goals",
        "known_user_info": "Known user information",
    }
    lines: list[str] = []
    for key, label in labels.items():
        values = [str(item) for item in (summary.get(key) or []) if str(item).strip()]
        if values:
            lines.append(f"- {label}: " + "; ".join(values))
    return "## Room Long-term Summary\n" + "\n".join(lines)


@dataclass(slots=True)
class RoomTurnContext:
    turns: list[dict[str, Any]]
    mode: str  # full | delta | windowed | rehydrated | transport_truncated
    cursor_before: int
    summary_block: str | None = None
    # Index the participant's thread owns everything up to after this turn is
    # delivered; used to advance the cursor exactly.
    cursor_after: int = 0
    # Whether this participant runs on a persistent thread that should track a
    # transcript cursor at all (False for stateless layered-context adapters).
    track_cursor: bool = False
    # Deterministically salvaged statements from turns that fell outside the
    # transported window.  Never empty when ``mode == transport_truncated``
    # and the room had older user turns.
    salvaged_facts: list[str] = field(default_factory=list)


def _estimate_transcript_bytes(turns: list[dict[str, Any]]) -> int:
    total = 0
    for turn in turns:
        if not isinstance(turn, dict):
            continue
        total += len(str(turn.get("content") or "").encode("utf-8"))
        total += len(str(turn.get("speaker_name") or "").encode("utf-8"))
    return total


def _trim_to_budget(
    turns: list[dict[str, Any]],
    budget_bytes: int,
    *,
    per_turn_chars: int = 600,
) -> list[dict[str, Any]]:
    """Keep the newest turns (and any user turn) inside a byte budget.

    Deterministic, no model call: newest-first greedy fill, user turns are
    never dropped before assistant turns because they carry the case facts.
    Per-turn cost uses the same estimator as the budget decision
    (content + speaker_name), so the result never exceeds the budget it
    was trimmed to (§32).  Both passes collect surviving ORIGINAL indices
    and the result is rebuilt in transcript order -- collecting turns
    directly would reverse() into an [all assistant]+[all user] interleave
    that scrambles the dialogue.
    """

    if _estimate_transcript_bytes(turns) <= budget_bytes:
        return list(turns)

    kept: list[tuple[int, dict[str, Any]]] = []
    used = 0
    # Pass 1: newest-first, user turns only.
    for index in range(len(turns) - 1, -1, -1):
        turn = turns[index]
        if not isinstance(turn, dict):
            continue
        if turn.get("participant_id") != "user":
            continue
        cost = _estimate_transcript_bytes([turn])
        if used + cost > budget_bytes:
            continue
        kept.append((index, turn))
        used += cost
    # Pass 2: fill the remainder with the newest assistant turns.
    for index in range(len(turns) - 1, -1, -1):
        turn = turns[index]
        if not isinstance(turn, dict):
            continue
        if turn.get("participant_id") == "user":
            continue
        content = str(turn.get("content") or "")
        cost = _estimate_transcript_bytes([turn])
        if used + cost > budget_bytes:
            remaining = budget_bytes - used
            if remaining <= 64:
                continue
            clipped = dict(turn)
            clipped["content"] = content[: per_turn_chars // 3] + "…"
            clipped_cost = _estimate_transcript_bytes([clipped])
            if used + clipped_cost > budget_bytes:
                continue
            kept.append((index, clipped))
            used += clipped_cost
            continue
        kept.append((index, turn))
        used += cost
    kept.sort(key=lambda pair: pair[0])
    return [turn for _, turn in kept]


@dataclass
class RoomContextManager:
    """Owns per-participant cursors and context-mode decisions."""

    cursor_enabled: bool = True
    raw_window: int = 8
    summary_every_turns: int = 10
    _cursors: dict[tuple[str, str], int] = field(default_factory=dict)
    _reset_pending: set[tuple[str, str]] = field(default_factory=set)
    delta_sends: int = 0
    rehydrations: int = 0
    _summary_lock: asyncio.Lock = field(default_factory=asyncio.Lock, repr=False)

    @staticmethod
    def _key(room_id: str, participant_id: str) -> tuple[str, str]:
        return (room_id, participant_id)

    def cursor_for(self, room_id: str, participant_id: str) -> int | None:
        return self._cursors.get(self._key(room_id, participant_id))

    def reset_cursor(self, room_id: str, participant_id: str) -> None:
        """Force context rehydration for one participant (thread was lost)."""

        key = self._key(room_id, participant_id)
        self._cursors.pop(key, None)
        self._reset_pending.add(key)

    def clear_room(self, room_id: str) -> None:
        for key in [k for k in self._cursors if k[0] == room_id]:
            self._cursors.pop(key, None)
        self._reset_pending.difference_update({k for k in self._reset_pending if k[0] == room_id})

    def prepare(
        self,
        *,
        room_id: str,
        participant_id: str,
        transcript: list[dict[str, Any]],
        persistent: bool,
        summary_block: str | None = None,
        transport_budget_bytes: int | None = None,
    ) -> RoomTurnContext:
        """Return the turns + mode that should compose the next prompt.

        ``transport_budget_bytes`` is the share of the adapter's prompt
        transport budget this turn may spend on raw transcript.  When the
        rolling summary is unavailable and the transcript no longer fits,
        the result is a deterministic truncation -- never a silent fallback
        to the full transcript, which is what used to blow past the ARGV
        ceiling and fail the turn with PROMPT_TRANSPORT_LIMIT_EXCEEDED.
        """

        key = self._key(room_id, participant_id)
        delivered_through = len(transcript)
        budget = (
            int(transport_budget_bytes)
            if transport_budget_bytes is not None
            else conservative_budget()
        )
        if persistent and self.cursor_enabled:
            cursor = self._cursors.get(key)
            if cursor is None:
                # Two distinct cold cases:
                # - explicit reset (thread was lost): rehydrate from kernel +
                #   summary + a bounded recent raw window.
                # - never tracked (participant joins a fresh room): deliver the
                #   whole history once so the new thread owns it, then go
                #   incremental.
                if key in self._reset_pending:
                    self._reset_pending.discard(key)
                    if transcript:
                        self.rehydrations += 1
                        return RoomTurnContext(
                            turns=list(transcript[-self.raw_window :]),
                            mode="rehydrated",
                            cursor_before=0,
                            summary_block=summary_block,
                            cursor_after=delivered_through,
                            track_cursor=True,
                        )
                    return RoomTurnContext(
                        turns=[], mode="delta", cursor_before=0, cursor_after=0
                    )
                if _estimate_transcript_bytes(transcript) > budget:
                    # A brand-new persistent thread must still be delivered
                    # something that fits on the wire; the older turns are
                    # salvaged as facts instead.
                    self.rehydrations += 1
                    window = _trim_to_budget(transcript, budget)
                    return RoomTurnContext(
                        turns=window,
                        mode="transport_truncated",
                        cursor_before=0,
                        summary_block=summary_block,
                        cursor_after=delivered_through,
                        track_cursor=True,
                        salvaged_facts=extract_older_user_facts(transcript),
                    )
                return RoomTurnContext(
                    turns=list(transcript),
                    mode="full",
                    cursor_before=0,
                    cursor_after=delivered_through,
                    track_cursor=True,
                )
            delta = list(transcript[cursor:])
            self.delta_sends += 1
            # The cursor protects against re-sending history, but a single
            # delta can still be larger than the transport can carry.
            if _estimate_transcript_bytes(delta) > budget:
                self.rehydrations += 1
                delta = _trim_to_budget(delta, budget)
                return RoomTurnContext(
                    turns=delta,
                    mode="transport_truncated",
                    cursor_before=cursor,
                    summary_block=summary_block,
                    cursor_after=delivered_through,
                    track_cursor=True,
                    salvaged_facts=extract_older_user_facts(transcript[cursor:]),
                )
            return RoomTurnContext(
                turns=delta,
                mode="delta",
                cursor_before=cursor,
                summary_block=summary_block,
                cursor_after=delivered_through,
                track_cursor=True,
            )
        # Stateless: bounded layered window instead of unbounded history.
        if len(transcript) > self.raw_window and summary_block:
            window = list(transcript[-self.raw_window :])
            if _estimate_transcript_bytes(window) > budget:
                window = _trim_to_budget(window, budget)
                return RoomTurnContext(
                    turns=window,
                    mode="transport_truncated",
                    cursor_before=len(transcript),
                    summary_block=summary_block,
                    cursor_after=delivered_through,
                    salvaged_facts=extract_older_user_facts(transcript),
                )
            return RoomTurnContext(
                turns=window,
                mode="windowed",
                cursor_before=len(transcript),
                summary_block=summary_block,
                cursor_after=delivered_through,
            )
        # No rolling summary to lean on: the raw window is the only context
        # there is.  Falling back to the *entire* transcript here is what
        # produced oversized ARGV prompts, so it is not allowed any more --
        # the transcript is truncated deterministically instead.
        if _estimate_transcript_bytes(transcript) > budget:
            return RoomTurnContext(
                turns=_trim_to_budget(transcript, budget),
                mode="transport_truncated",
                cursor_before=len(transcript),
                summary_block=summary_block,
                cursor_after=delivered_through,
                salvaged_facts=extract_older_user_facts(transcript),
            )
        return RoomTurnContext(
            turns=list(transcript),
            mode="full",
            cursor_before=len(transcript),
            cursor_after=delivered_through,
        )

    def commit(self, room_id: str, participant_id: str, ctx: RoomTurnContext) -> None:
        """Advance the cursor after the prompt was delivered to the runtime."""

        if ctx.track_cursor:
            # A persistent thread now owns everything up to cursor_after.
            self._cursors[self._key(room_id, participant_id)] = ctx.cursor_after
        # Stateless participants keep no cursor; every turn is a fresh window.

    def should_update_summary(self, turn_index: int) -> bool:
        if turn_index < self.raw_window:
            return False
        return turn_index % max(4, self.summary_every_turns) == 0

    async def update_summary(
        self,
        *,
        transcript: list[dict[str, Any]],
        previous_summary: str | None,
        summarize: Any,
    ) -> str | None:
        """Regenerate the durable rolling summary via one model call.

        ``summarize`` is an async callable (prompt, schema) -> dict; injected
        so the manager never touches adapters directly.
        """

        if not transcript:
            return previous_summary
        async with self._summary_lock:
            window = transcript[-(self.summary_every_turns + self.raw_window) :]
            payload = {
                "previous_summary": previous_summary or "",
                "new_turns": [
                    {
                        "speaker": t.get("speaker_name") or t.get("persona_id"),
                        "content": str(t.get("content") or "")[:1200],
                    }
                    for t in window
                ],
            }
            try:
                result = await summarize(payload, SUMMARY_SCHEMA)
            except Exception:
                return previous_summary
            if isinstance(result, dict):
                return render_summary_markdown(result)
            return previous_summary

    def snapshot(self) -> dict[str, Any]:
        return {
            "cursor_enabled": self.cursor_enabled,
            "raw_window": self.raw_window,
            "tracked_participants": len(self._cursors),
            "delta_sends": self.delta_sends,
            "rehydrations": self.rehydrations,
        }


__all__ = [
    "RoomContextManager",
    "RoomTurnContext",
    "SUMMARY_PROMPT_INTRO",
    "SUMMARY_SCHEMA",
    "render_summary_markdown",
]
