from __future__ import annotations

import copy
from typing import Any

from persona_continuum.world.models import Actor, ActorRuntimeConfig, ActorType, WorldSeed

AGENT_CAPABLE_ACTOR_TYPES = {
    ActorType.PERSONA_ACTOR,
    ActorType.ORGANIZATION_ACTOR,
    ActorType.INSTITUTION_ACTOR,
    ActorType.COLLECTIVE_ACTOR,
    # Legacy values remain decision-capable for worlds created before the
    # unified Profile Library migration.
    ActorType.PERSISTENT_PERSONA,
    ActorType.GENERATED_ACTOR,
    ActorType.ORGANIZATION,
}


class ActorManager:
    """Manages actors within a parallel world simulation branch."""

    def __init__(self) -> None:
        self._actors: dict[str, Actor] = {}

    def initialize_actors_for_world(
        self,
        seed: WorldSeed,
        default_runtime: ActorRuntimeConfig | None = None,
    ) -> dict[str, Actor]:
        actors: dict[str, Actor] = {}

        # 1. Check if explicit actor metadata was generated by LLM World Builder
        raw_meta_actors = seed.metadata.get("initial_actors", [])
        classified_metadata = seed.metadata.get("entity_classification", {})
        non_agent_ids = {
            str(item.get("id"))
            for item in (
                classified_metadata.get("non_agent_entities", [])
                if isinstance(classified_metadata, dict)
                else []
            )
            if isinstance(item, dict) and item.get("id")
        }
        if isinstance(raw_meta_actors, list) and raw_meta_actors:
            for item in raw_meta_actors:
                if isinstance(item, dict) and "id" in item:
                    is_non_agent = item.get("entity_category") == "non_agent"
                    if is_non_agent or str(item["id"]) in non_agent_ids:
                        # Policies, events, resources and other initial
                        # conditions belong in WorldState/causal graph, not in
                        # the autonomous Actor roster.
                        continue
                    aid = str(item["id"])
                    raw_type = item.get("actor_type", "persona_actor")
                    valid_types = {t.value for t in ActorType}
                    atype = (
                        ActorType(raw_type) if raw_type in valid_types else ActorType.PERSONA_ACTOR
                    )
                    profile_type = str(item.get("profile_type") or "") or None
                    if profile_type == "institution":
                        atype = ActorType.INSTITUTION_ACTOR
                    elif profile_type == "collective":
                        atype = ActorType.COLLECTIVE_ACTOR
                    elif profile_type == "organization":
                        atype = ActorType.ORGANIZATION_ACTOR
                    if not profile_type:
                        profile_type = {
                            ActorType.ORGANIZATION_ACTOR.value: "organization",
                            ActorType.INSTITUTION_ACTOR.value: "institution",
                            ActorType.COLLECTIVE_ACTOR.value: "collective",
                        }.get(atype.value)
                    actors[aid] = Actor(
                        id=aid,
                        name=item.get("name", aid.replace("_", " ").title()),
                        actor_type=atype,
                        persona_id=(
                            item.get("persona_id") or aid
                            if profile_type in {None, "person"}
                            else None
                        ),
                        profile_id=item.get("profile_id"),
                        profile_type=profile_type,
                        organization_id=item.get("organization_id"),
                        identity=item.get("identity", {"role": item.get("name", aid)}),
                        goals=item.get("goals", []),
                        beliefs=item.get("beliefs", {}),
                        relationships=item.get("relationships", {}),
                        resources=item.get("resources", {}),
                        memory=[
                            {
                                "occurred_at": seed.start_date,
                                "content": f"Initialized at timeline start {seed.start_date}",
                            }
                        ],
                    )

        # 2. Add actors specified by ID in seed.initial_actors
        for aid in seed.initial_actors:
            if str(aid) in non_agent_ids:
                continue
            if aid not in actors:
                actors[aid] = Actor(
                    id=aid,
                    name=aid.replace("_", " ").title(),
                    actor_type=ActorType.PERSONA_ACTOR,
                    persona_id=aid,
                    identity={"role": "Key Decision Maker"},
                    goals=[f"Pursue strategic interests in the {seed.baseline_world} timeline"],
                    beliefs={},
                    relationships={},
                    resources={},
                    memory=[
                        {
                            "occurred_at": seed.start_date,
                            "content": f"Initialized at timeline start {seed.start_date}",
                        }
                    ],
                )

        # 3. Add organizations from seed metadata
        raw_orgs = seed.metadata.get("organizations", [])
        if isinstance(raw_orgs, list):
            for org in raw_orgs:
                if isinstance(org, dict) and "id" in org:
                    oid = str(org["id"])
                    if oid not in actors:
                        actors[oid] = Actor(
                            id=oid,
                            name=org.get("name", oid.replace("_", " ").title()),
                            actor_type=ActorType.ORGANIZATION_ACTOR,
                            organization_id=oid,
                            identity={"sector": org.get("sector", "Industry")},
                            goals=org.get("goals", ["Grow organizational capacity and capability"]),
                            resources={
                                "cash_reserves_billions": org.get("cash_reserves_billions", 1.0),
                                "engineers_count": org.get("headcount_engineers", 100),
                            },
                            memory=[],
                        )

        # 4. No fallback roster: worlds with no explicit actors simply start
        # with an empty actor list (domain-agnostic engine default).

        # Apply Profile Library classification bindings before runtime binding.
        classified = seed.metadata.get("entity_classification", {})
        classified_rows = (
            classified.get("classified_agents", [])
            if isinstance(classified, dict)
            else []
        )
        classified_by_id = {
            str(item.get("id")): item
            for item in classified_rows
            if isinstance(item, dict) and item.get("id")
        }
        subtype_to_actor_type = {
            "organization": ActorType.ORGANIZATION_ACTOR,
            "institution": ActorType.INSTITUTION_ACTOR,
            "collective": ActorType.COLLECTIVE_ACTOR,
            "person": ActorType.PERSONA_ACTOR,
        }
        for actor in actors.values():
            row = classified_by_id.get(actor.id)
            if not row:
                continue
            actor.profile_id = row.get("profile_id")
            actor.profile_type = row.get("subtype")
            actor.actor_type = subtype_to_actor_type.get(
                str(row.get("subtype")), actor.actor_type
            )

        # Apply runtime bindings & configs
        configured = seed.metadata.get("actor_runtime_configs", {})
        configured = configured if isinstance(configured, dict) else {}
        for actor in actors.values():
            actor_config = configured.get(actor.id)
            if isinstance(actor_config, dict):
                runtime = ActorRuntimeConfig.model_validate(
                    {
                        "persona_id": actor.persona_id or "",
                        "profile_id": actor.profile_id,
                        "profile_type": actor.profile_type,
                        **actor_config,
                    }
                )
            elif default_runtime is not None and actor.actor_type in AGENT_CAPABLE_ACTOR_TYPES:
                runtime = default_runtime.model_copy(
                    update={
                        "persona_id": actor.persona_id or "",
                        "profile_id": actor.profile_id,
                        "profile_type": actor.profile_type,
                    }
                )
            else:
                runtime = ActorRuntimeConfig(
                    persona_id=actor.persona_id or "",
                    profile_id=actor.profile_id,
                    profile_type=actor.profile_type,
                    agent_id="unconfigured",
                    model_id="auto",
                    credential_provider="unconfigured",
                    inherit_default_runtime=False,
                )
            actor.runtime_config = runtime
            actor.persona_id = runtime.persona_id
            actor.agent_runtime_id = runtime.agent_id
            actor.model_id = runtime.model_id

        self._actors = actors
        return copy.deepcopy(self._actors)

    def get_actor(self, actor_id: str) -> Actor | None:
        actor = self._actors.get(actor_id)
        return copy.deepcopy(actor) if actor else None

    def list_actors(self) -> list[Actor]:
        return [copy.deepcopy(a) for a in self._actors.values()]

    def update_actor(self, actor: Actor) -> None:
        self._actors[actor.id] = copy.deepcopy(actor)

    def append_memory(self, actor_id: str, memory_item: dict[str, Any]) -> None:
        if actor_id in self._actors:
            self._actors[actor_id].memory.append(memory_item)
